	.title	"ZID (Z80 In-circuit Debugger) Debugger Monitor"
	.stitle	"Boot (full reset) Initialization, Breakpoint, or DOC ATTN"
;
; Debug Monitor for Z80 In-circuit Debugger (ZID)
;
; Copyright 2025-26 AESilky
; SPDX-License-Identifier: MIT License
;
BOOT		.sect	W
;		.org	0

		.list	1		; 1 = Don't list these included files, >=2 will list
		.input	"board.inc"
		.input	"storage.inc"
		.input	"doccmds.inc"
		.input	"diag/diag.inc"

; ===========================
; The Debug Monitor performs the board initialization and handles the Z80 Special Reset SPRST
; that is used to regain control from target code execution when a breakpoint is hit or the
; Debug Operation Controller (DOC) signals that it wants attention (ATTN). DOC ATTN is
; signaled be an NMI when the system is in debug mode (haven't started, or have broken out of
; target mode).
;
; After board initialization is complete, the Debug Monitor does not use the alternate
; register set and doesn't disable or enable interrupts or change the interrupt mode
; (as regular interrupts are not used in debug mode)). Therefore, when the user changes
; those registers, enables or disables interrupts, or changes the interrupt mode, those
; changes are immediately applied. This speeds up single-step operations and going into
; target mode.
;
; The contents of RAM are subject to being overwritten if the target is the SBC, as it may
; map in the region of RAM the ZID uses and modify it. Therefore, the section of RAM that
; stores the breakpoint information is check-summed. If it is found to be incorrect the
; breakpoint information is requested from the DOC to restore it.
;
; ===========================

; ===========================
;
; ROUTINE: boot - Full/Init or Breakpoint Hit or ATTN from RPM when in Target Mode.
;
; PURPOSE: Configure the board or handle a Z80 Special Reset (breakpoint or ATTN).
;
; ENTRY: _
; EXIT:  _
;
; ===========================
;
boot:
		nop				; 2 NOPs to allow for forced NOP being executed
		nop				;  during SPRST
		jp	bahdlr			; Break & Attn Handler
rst08:		.org	boot+08h
		nop
		nop
		jp	bar8hdlr		; ! RST8 used in place of SPRST when debugging with ZED
rst10:		.org	boot+10h
		jp	onrst10
rst18:		.org	boot+18h
		jp	onrst18
rst20:		.org	boot+20h
		jp	onrst20
rst28:		.org	boot+28h
		jp	onrst28
rst30:		.org	boot+30h
		jp	onrst30
rst38:		.org	boot+38h
		jp	onrst38
		
		.org	boot+40h
id:		.byte	"ZID DEBUG MONITOR:"	; ID
		.align	2
ver:		.equ	$
		.input	"version.inc"		; build date/version
_ver:		.byte	0
nmivec:		.org	boot+66h
		jp	rdyforcmd		; DOC ATTN when in Debug Mode uses NMI

		.align	4
		;--------------------------------------------------------------
		; Break|ATTN handler from RST8 (for debugging with ZED)
		; ! ZZZ the breadboard doesn't have the PC latch, so
		; ! we'll (try to) get the PC off the stack and then handle
		; ! like a SPRST
		;
bar8hdlr:	.equ	$
		ld	(tempsp),sp
		ld	sp,tempsp
		push	af			; we can now use AF and SP
		ld	a,(zflag)
		set	zf_dbzed,a		; indicate that we are debugging with ZED (RST8 rather than SPRST)
		ld	(zflag),a
		jp	dbzent

		.org	boot+0100h
		;--------------------------------------------------------------
		; This could be a Single-Step, Break, or DOC asking for attention
		; Or it could be a FULL RESET
		; Treat as SS/BRK or ATTN until we figure out for sure (save AF and SP)
		;
bahdlr:		.equ	$
		ld	(tempsp),sp
		ld	sp,tempsp
		push	af			; we can now use AF and SP
dbzent:		in	a,(PCADDR_RD)		; read the PC-b0 and status. this will allow us to see if the
		ld	(brk_pc_inf),a		; reset is from a BRK or ATTN. Or,
		bit	ZIDINITD_B,a		; if the ZID isn't initialized treat as Full Reset
		jp	z,doinit		;  Do the initialization
		; Check for SS, Break, or ATTN
		; First, see if it is SS (as BRK will also be indicated for SS)
		in	a,(BRDCTRL)
		bit	SSTEP_B,a
		jr	nz,_ss
		; Break (hard or soft) or Attention?
		ld	a,(brk_pc_inf)
		and	SR_ISHBRK_M|SR_ISSBRK_M|ATTN_ON_M
		jr	nz,_brkattn
		; Odd, It wasn't SS, BRK, or ATTN, but Init'ed bit was on??? Go (re)init...
		jp	doinit
_ss:
		ld	(sspflag),a		; SS flag to non-zero
		; Clear the Single-Step control bit
		and	~SSTEP_M
		out	(BRDCTRL),a
_brkattn:	; SS/BRK or Attention Common
		; Save the rest of the registers
		ld	sp,rpushiy_		; Target SP already in 'tempsp' and af pushed on tempsp
		push	iy
		push	ix
		ld	sp,regf
		push	hl
		push	de
		push	bc
		; do the alternates
		ex	af,af'
		exx
		push	hl
		push	de
		push	bc
		push	af
		; put the primaries back (the DM doesn't use the alternate registers after init)
		exx
		ex	af,af'
		; get the IV and IE state
		ld	a,i
		push	af		; this saves i and p/v which indicates Ints Enabled/Disabled
		; we have the state of IFF2, disable ints (we don't use them)
		di
		;
		; Read in and build up the saved PC
		ld	a,(zflag)
		bit	zf_dbzed,a
		; ZZZ For now, always using pushed PC jr	z,sr1		; Special Reset => (not RST8 (ZED/SELF) debugging)
		;
		; Debugging using RST8 rather than SPRST (to allow ZED to be used)
		;  try to get the PC from the stack (pushed by the RST8)
		;
		res	zf_dbzed,a	; clear the DB-ZED flag for next BRK/ATTN
		ld	(zflag),a
		ld	sp,tempaf	; get the target 'sp' and 'af' saved initially
		pop	bc		; 'AF' into BC
		ld	sp,dbmstk	; set our stack (for the calls below)
		ld	hl,(tempsp)	; get the saved SP into HL
		; try to get the PC
		ld	e,(hl)		; low byte
		inc	hl
		ld	d,(hl)		; high byte
		; Since the forced RST8 instruction was executed, the pushed PC is actually 1 too much
		dec	de		; Now DE has the correct PC
		inc	hl		; Now HL has correct SP
		ld	(tempsp),hl	; save for resuming
		; registers now match what SPRST builds up below: PC in DE, SP in HL, AF in BC
		jr	sr2		;  so bypass the PC read & build steps
		;	
sr1:		; bit-15 was read to get the break status, get it back and build up the rest
		xor	a
		ld	d,a
		ld	e,a
		ld	a,(brk_pc_inf)
		; do the upper byte
		ld	b,8
pcrd1:		and	00000001b
		sla	d
		or	d
		ld	d,a
		in	a,(PCADDR_RD)	; each read reads 1 bit from 14 to 0 (15 was read at reset)
		djnz	pcrd1
		; do the lower byte
		ld	b,8
pcrd2:		and	00000001b
		sla	e
		or	e
		ld	e,a
		in	a,(PCADDR_RD)
		djnz	pcrd2
		; DE now contains the PC saved by the Special Reset
		ld	sp,tempaf	; get the target 'sp' and 'af' saved initially
		pop	bc		; 'af' into bc
		pop	hl		; 'sp'
		;
sr2:		; target: PC in DE, SP in HL, AF in BC
		ld	sp,regsav2
		push	iy		; do IY and IX now, so the 2-byte registers are together
		push	ix
		push	de		; PC
		push	hl		; SP
		push	bc		; AF
		; All target registers and the Ints-Enabled state saved 
		ld	sp,dbmstk	; Set the Debug Monitor Stack
		;
		; Was this SPRST from a breakpoint, single-step, or ATTN
		;
		ld	a,(brk_pc_inf)
		bit	ATTN_ON_B,a
		jr	nz,srattn	; DOC poked us, say we are ready and read a command...
		and	SR_ISHBRK_M|SR_ISSBRK_M
		ld	a,DMBRKHIT	; Hard or Soft Breakpoint =>
		jp	nz,doc_statsend	; Send our status and go idle...
		; Single-Step?
		ld	a,(sspflag)
		or	a
		ld	a,DMSSDONE
		jp	nz,doc_statsend	; Send our status and go idle...
		;
		; Odd... not SS??? Just fall through to saying we are ready and reading a command.
srattn:		;
		; ATTN...
		ld	a,DMOKCMDRD
		jp	doc_cmdrd


	.stitle	"RESTART Handlers"
		.align	4
;; =============
;; Restart Handlers - None of these are expected.
;;
;; Load B with the RST Number and jump to a common routine to
;; send a status to the DOC and HALT
;;
onrst10:	ld	b,10h
		jr	onrst
onrst18:	ld	b,18h
		jr	onrst
onrst20:	ld	b,20h
		jr	onrst
onrst28:	ld	b,28h
		jr	onrst
onrst30:	ld	b,30h
		jr	onrst
onrst38:	ld	b,38h
		jr	onrst
		.align	4	; to aid debugging
onrst:		; Send an error status to DOC and HALT (lights the HALT LED)
		ld	a,DMRSTEXEC
		out	(RPMCTRL),a
		halt		; Doc can wake us up if it wants


	.stitle	"TARGET Operations"
		.align	4
;;**************
;; @brief `tgtgo` Run the target code.
;; @ingroup dbmon
;;
;; Restores the target registers, notifies DOC that we are transitioning
;; to Target Mode, triggers the TGT_GO count down, loads the target PC
;; in the jump location, then jumps to the (ram located) target jump -
;; this is referred to as the, 'HOP, SKIP, and JUMP' to the Target.
;; 
;; @entry
;;	Target registers and requested PC in our Target Storage Locations
;;**************
tgtgo:		; make sure Single-Step is off
		in	a,(BRDCTRL)
		and	~SSTEP_M
		out	(BRDCTRL),a
		jr	tgthop
		.align	4		; to aid debugging
tgtstep:	; set operation to Single-Step
		in	a,(BRDCTRL)
		or	SSTEP_M
		out	(BRDCTRL),a
		;
		; Common 'HOP' code for GO and Single-Step
		;
tgthop:		; put the JP instruction in ram for the Target hop, skip, jump
		ld	a,JP_OP
		ld	(tgtskip),a
		ld	a,DMTGTGO	; Tell DOC we are going to Target Mode (RUN or SingleStep)
		out	(RPMCTRL),a	;  so we don't want it to bother us for a while!
		xor	a
		ld	(sspflag),a	; clear SS performed flag
		ld	sp,(regpc)	; Get Target PC and put
		ld	(tgtjump),sp	; into ram at the JP instruction
		;
		; restore the target registers...
		; Note: IV, and alternates are always valid
		;	(they aren't used by the DM), so there is no
		;	need to restore them.
		;
		ld	sp,rpopix_
		pop	ix
		pop	iy
		ld	sp,regsav_
		pop	bc
		pop	de
		pop	hl
		;
		; don't do AF and SP until we are ready to go
		;
		; do interrupt enable/disable
		ld	a,(regied)
		bit	ie_b,a		; ints enabled?
		jr	z,tgthop1
		ei
tgthop1:	ld	sp,rstgtgo_	; get ready to get AF
		pop	af		; get AF
		out	(TGTGO),a	; And the countdown begins:
		ld	sp,(regsp)	; get SP	[mem_op: 1,2,3,4, 5,6]
		nop			; [mem_op: 7]
		nop			; [mem_op: 8]
		nop			; [mem_op: 9]
					; done with HOP. Now...
		jp	tgtskip		; skip & jump to target [mem_op: 10,11,12]
					; (SKIP,JUMP are [mem_op: 13,14,15 - 16 in TGT])

		.align	4		; to aid debugging
	.stitle	"Target Write Byte"
;;**************
;; @brief `twrbyte` Write the byte in E to the target address in HL.
;; @ingroup dbmon
;;
;; @entry
;;	E: Byte to write
;;	HL: Address
;; @uses
;;	A
;;**************
twrbyte:	ld	a,(zflag)
		bit	zf_usezid,a	; Use the ZID's memory?
		jr	nz,wrbytez	;  yes->
		; set Single-Op
		in	a,(BRDCTRL)
		or	SOP_M
		out	(BRDCTRL),a
		out	(TGTGO),a	; Countdown begins:
		nop			; MEMOP 1
		nop			; MEMOP 2
		nop			; MEMOP 3
		nop			; MEMOP 4
		nop			; MEMOP 5
		nop			; MEMOP 6
		nop			; MEMOP 7
		nop			; MEMOP 8
		nop			; MEMOP 9
		nop			; MEMOP 10
		nop			; MEMOP 11
		nop			; MEMOP 12
		nop			; MEMOP 13
		nop			; MEMOP 14
wrbytez:	ld	(hl),e		; MEMOP 15 - MEMOP 16 write the byte
		; clear Single-Op
		and	~SOP_M
		out	(BRDCTRL),a
		ret

		.align	4
_twrbyte:	ld	sp,dbmstk
		call	twrbyte
		jp	idle	

		.align	4		; to aid debugging
	.stitle	"Target Read Byte"
;;**************
;; @brief `trdbyte` Read a byte from the target address in HL into E.
;; @ingroup dbmon
;;
;; @entry
;;	HL: Address
;; @uses
;;	A
;; @return
;;	E: Byte read
;;**************
trdbyte:	ld	a,(zflag)
		bit	zf_usezid,a	; Use the ZID's memory?
		jr	nz,rdbytez	;  yes->
		; set Single-Op
		in	a,(BRDCTRL)
		or	SOP_M
		out	(BRDCTRL),a
		out	(TGTGO),a	; Countdown begins:
		nop			; MEMOP 1
		nop			; MEMOP 2
		nop			; MEMOP 3
		nop			; MEMOP 4
		nop			; MEMOP 5
		nop			; MEMOP 6
		nop			; MEMOP 7
		nop			; MEMOP 8
		nop			; MEMOP 9
		nop			; MEMOP 10
		nop			; MEMOP 11
		nop			; MEMOP 12
		nop			; MEMOP 13
		nop			; MEMOP 14
rdbytez:	ld	e,(hl)		; MEMOP 15 - MEMOP 16 read the byte
		; clear Single-Op
		and	~SOP_M
		out	(BRDCTRL),a
		ret

		.align	4
_trdbyte:	ld	sp,dbmstk
		call	trdbyte
		jp	idle

		.align	4		; to aid debugging
	.stitle	"Target Out Byte"
;;**************
;; @brief `toutbyte` Output the byte in E to the target port in BC.
;; @ingroup dbmon
;;
;; @entry
;;	E: Byte to output
;;	BC: Address
;; @uses
;;	A
;;**************
toutbyte:	ld	a,(zflag)
		bit	zf_usezid,a	; Use the ZID's port?
		jr	nz,obytez	;  yes->
		; set Single-Op
		in	a,(BRDCTRL)
		or	SOP_M
		out	(BRDCTRL),a
		out	(TGTGO),a	; Countdown begins:
		nop			; MEMOP 1
		nop			; MEMOP 2
		nop			; MEMOP 3
		nop			; MEMOP 4
		nop			; MEMOP 5
		nop			; MEMOP 6
		nop			; MEMOP 7
		nop			; MEMOP 8
		nop			; MEMOP 9
		nop			; MEMOP 10
		nop			; MEMOP 11
		nop			; MEMOP 12
		nop			; MEMOP 13
obytez:		out	(c),e		; MEMOP 14&15 - 16 output the byte
		; clear Single-Op
		in	a,(BRDCTRL)	; need to re-read,
		and	~SOP_M		;  as the OUT could have changed it
		out	(BRDCTRL),a
		ret

		.align	4
_toutbyte:	ld	sp,dbmstk
		call	toutbyte
		jp	idle


		.align	4		; to aid debugging
	.stitle	"Target In Byte"
;;**************
;; @brief `tinbyte` Input a byte from the target port in BC into E.
;; @ingroup dbmon
;;
;; @entry
;;	BC: Address
;; @uses
;;	A
;; @return
;;	E: Byte input
;;**************
tinbyte:	ld	a,(zflag)
		bit	zf_usezid,a	; Use the ZID's memory?
		jr	nz,inbytez	;  yes->
		; set Single-Op
		in	a,(BRDCTRL)
		or	SOP_M
		out	(BRDCTRL),a
		out	(TGTGO),a	; Countdown begins:
		nop			; MEMOP 1
		nop			; MEMOP 2
		nop			; MEMOP 3
		nop			; MEMOP 4
		nop			; MEMOP 5
		nop			; MEMOP 6
		nop			; MEMOP 7
		nop			; MEMOP 8
		nop			; MEMOP 9
		nop			; MEMOP 10
		nop			; MEMOP 11
		nop			; MEMOP 12
		nop			; MEMOP 13
inbytez:	in	e,(c)		; MEMOP 14&15 - 16 input the byte
		; clear Single-Op
		and	~SOP_M
		out	(BRDCTRL),a
		ret

		.align	4
_tinbyte:	ld	sp,dbmstk
		call	tinbyte
		jp	idle


	.stitle	"DOC (Debug Operations Controller) Interaction"
		.align	4
;; =============
;; Send DOC our status repeatedly until DOC indicates it is ready
;;
;; @Params
;;	A: Status to send (SBC bit is or'ed in)
;; @Used
;;	B; Counter
;;	E: Holds status (A)
;;	D: Holds DOC status
;;	HL: Counter
;; @Return
;;	NO - This goes IDLE waiting for wake-up by DOC
;;
doc_wrdy:	ld	a,DMINIT
		ld	hl,sflag
		or	(hl)
		ld	e,a
_dwr1:		out	(RPMCTRL),a
		in	a,(RPMCTRL)
		ld	d,a
		cp	DOCREADY
		jp	z,go_idle	; It is ready and so are we... Go Idle
		;
		; DOC isn't ready yet, delay some and try again
		;
		xor	a
		ld	b,a
_dwr_w1:	dec	a
		jr	nz,_dwr_w1
		djnz	_dwr_w1
		; okay, some time has passed - try DOC again
		ld	a,e
		jr	_dwr1		

		.align	4
;; =============
;; Send DOC our status and then go IDLE
;;
;; @Params
;;	A: Status to send (SBC indicator bit is or'ed in)
;; @Return
;;	NO - This goes IDLE waiting for wake-up by DOC
;;
;; `doccmddone` sets A to OPERATION DONE OKAY status and falls into `doc_statsend`
doc_opdone:	ld	a,DMOPDONE
doc_statsend:	ld	hl,sflag
		or	(hl)
		out	(RPMCTRL),a
go_idle:	ld	sp,dbmstk
idle:		jr	idle		; Wait for the DOC to ask us to do something

		.align	4
doc_cmdrd:	ld	hl,sflag
		or	(hl)
		out	(RPMCTRL),a	; on ATTN this returns quickly. DMBRKHIT takes longer due to waking DOC up.
		in	a,(RPMCTRL)
		;
		; Check that the DM/DC bit (bit-7) is set. Otherwise this isn't for us.
		bit	DM_CMD_STAT_B,a
		jr	z,go_idle
		cp	DOCREADY	; if it's just their 'READY' status, send ours
		jr	z,doc_wrdy
		;
		; process the DOC command
		;
		ld	(doc_cmd),a
		jp	doccmdprc

		.align	4
		; DOC wants ATTN, or our very first interaction after reset.
		; We are already in Debug Mode so no need to do any register saving.
		; We come here from an NMI (or initial boot), but no need to return.
rdyforcmd:	ld	a,DMOKCMDRD	; Tell DOC we're ready for a command
		jr	doc_cmdrd


		.align	4
;; =============
;; Get an address and count from DOC.
;;
;; @Used:
;;	A, C
;; Return:
;;	HL: address from DOC
;;	B: count
;;
doc_gaddrcnt:	ld	c,RPMDATA
		in	l,(c)
		in	h,(c)
		in	b,(c)
		ld	a,l
		ld	(doc_addr),a
		ld	a,h
		ld	(doc_addr+1),a
		ld	a,b
		ld	(doc_cnt),a
		ret

		.align	4
;; =============
;; Get a buffer of values from DOC.
;;
;; @Used:
;;	A, B, C, H, L
;; @Result:
;;	doc_addr = Address received
;;	doc_cnt	 = Count received
;;	doc_buf  = Data received
;; @Return:
;;	B: Count
;;	HL: Address
;;
doc_gdata:	.equ	$
		call	doc_gaddrcnt
		ld	hl,doc_buf
		ld	c,RPMDATA
		inir
		ld	hl,(doc_addr)
		ld	a,(doc_cnt)
		ld	b,a
		ret

		.align	4
;; =============
;; Send a buffer of values to DOC.
;;
;; @Expects:
;;	doc_cnt  = Count to send
;;	doc_buf  = Data to send
;; @Uses:
;;	A, B, C, H, L
;;
doc_sdata:	.equ	$
		ld	a,(doc_cnt)
		ld	b,a
		ld	hl,doc_buf
		ld	c,RPMDATA
		otir
		ret

		.align	4
;; =============
;; Process a DOC command
;;
;; @Params
;;	A: Command from DOC (also in 'doc_cmd')
;; @Used
;;	A, C
;;
doccmdprc:	; ZZZ - When we process more commands, maybe use a jump table?
		;	In the grand scheme of things, this doesn't take a lot
		;	of time or memory, and it's easy to understand and debug.
		cp	DCNOP
		jp	z,do_nop
		;
		cp	DCGM
		jp	z,do_gmem
		;
		cp	DCGP
		jp	z,do_gport
		;
		cp	DCGREGALL
		jp	z,do_gregall
		;
		cp	DCPM
		jp	z,do_pmem
		;
		cp	DCPP
		jp	z,do_pport
		;
		cp	DCPREGALL
		jp	z,do_pregall
		;
		cp	DCGO
		jp	z,do_go
		;
		cp	DCGOWREG
		jp	z,do_gowreg
		;
		cp	DCSTEP
		jp	z,do_step
		;
		cp	DCSTEPWREG
		jp	z,do_stepwreg
		;
		cp	DCVER
		jp	z,do_ver
		;
		;
		; If the DOC just woke up, we might get its ready status
		; in place of a command, so handle it by just saying
		; 'okay we are done'.
		cp	DOCREADY
		jp	z,doc_opdone
		;
		; Command unknown (or not yet supported)
		ld	a,DMCMDUK
		jp	doc_statsend

		.align	2
do_nop:		; NO OPERATION
		jp	doc_opdone

		.align	2
do_ver:		; Get the Version
		ld	hl,ver
		ld	b,_ver-ver
		ld	c,RPMDATA
		otir
		jp	doc_opdone

		.align	2
do_gowreg:	; TARGET GO with REGISTERS
		ld	hl,regied
		ld	b,ZREGBYTES
		ld	c,RPMDATA
		inir
		; fall through to GO...
		;
do_go:		; TARGET GO (from the current PC)
		jp	tgtgo

		.align	2
do_gmem:	; Send memory to DOC
		;  READ: Addr, Count
		call	doc_gaddrcnt
		ld	ix,doc_buf
_gmem:		; Get the bytes into the buffer
		call	trdbyte;
		ld	(ix),e
		inc	hl
		inc	ix
		djnz	_gmem
		; data is in buffer, send it to DOC
		call	doc_sdata
		jp	doc_opdone

		.align	2
do_gport:	; Send port values to DOC
		;  READ: Addr, Count
		call	doc_gaddrcnt
		ld	ix,doc_buf
		ld	c,l
_gport:		; Get the values into the buffer
		ld	d,b	; save count
		ld	b,h	; upper address into b
		call	tinbyte;
		ld	(ix),e
		inc	ix
		ld	b,d
		djnz	_gport
		; data is in buffer, send it to DOC
		call	doc_sdata
		jp	doc_opdone

		.align	2
do_pmem:	; Get values from DOC and put in Target memory
		call	doc_gdata
		ld	ix,doc_buf
_pmem:		ld	e,(ix)
		call	twrbyte
		inc	hl
		inc	ix
		djnz	_pmem
		jp	doc_opdone

		.align	2
do_pport:	; Get values from DOC and output to Target port
		call	doc_gdata
		ld	ix,doc_buf
		ld	c,l
_pport:		; Put the values from the buffer
		ld	d,b	; save count
		ld	b,h	; upper address into b
		ld	e,(ix)	; value
		call	toutbyte
		inc	ix
		ld	b,d
		djnz	_pport
		jp	doc_opdone

		.align	2
do_gregall:	; Send all the registers to DOC
		ld	hl,regied
		ld	b,ZREGBYTES
		ld	c,RPMDATA
		otir
		jp	doc_opdone

		.align	2
do_pregall:	; Receive all the registers from the DOC
		ld	hl,regied
		ld	b,ZREGBYTES
		ld	c,RPMDATA
		inir
		jp	doc_opdone

		.align	2
do_stepwreg:	; TARGET STEP with REGISTERS
		ld	hl,regied
		ld	b,ZREGBYTES
		ld	c,RPMDATA
		inir
		; fall through to STEP...
		;
do_step:	; TARGET STEP (from the current PC)
		jp	tgtstep


		.align	4
	.stitle	"Debug Operations"

set_im0:	im	0
		ld	a,i
		jp	idle

		.align	4
set_im1:	im	1
		ld	a,i
		jp	idle

		.align	4
set_im2:	im	2
		ld	a,i
		jp	idle


		.align	4
	.stitle	"Initialization"
;; =============
;; Debug Monitor (and board) Initialization.
;;
;; The board has just done a Full Reset (power on or push button)
;; Initialize the required functionality of the board and set up the Debug Monitor (DM)
;;
;; The PC and AF registers were saved in RAM in case it was a Special Reset (SPRST)
;; for a Breakpoint Hit or DOC Attention, but it was determined that it was a Power-On
;; or Push-Button (full) reset, so those values aren't needed.
;;
;; To initialize, we do:
;; 1) RAM Test (verify the operation of the DM section of the RAM)
;; 2) Fill RAM with 0 (assuming the test passed)
;; 3) Determine the number of Breakpoint Address Units
;; 4) Initialize memory structures for the breakpoint units (both 1 and 2N)
;; 5) Set the CPLD flag indicating that ZID-DM Init is completed
;; 6) Notify the DOC that initialization is complete, or that it failed
;;
;; This is the only place that we use the IY register. Once initialization is complete
;; only the primary base registers are used.
;;
doinit:		ld	iy,init2	; IY holds the address to return to (as we clobber ram)
		ld	hl,DB_RAMBASE
		ld	c,DB_RAMPC
		jp	ramchk_ns	; test our ram (note that we don't test the whole board)
		jr	z,init2		;  passed...
		; !!! MEMORY ERROR !!!
		; HL hold address of error, A expected, E read
		; continuously write and read it (read to D to not mess up E)
imemerr:	ld	(hl),a
		ld	d,(hl)
		jr	imemerr
init2:		; fill ram with 0
		ld	hl,DB_RAMBASE
		ld	(hl),0
		ld	de,DB_RAMBASE+1
		ld	bc,(DB_RAMPC*ONE_PAGE)-1
		ldir
		;
		; Determine how many Breakpoint Address Units (BAU) there are.
		; 1 & 2 are on the main board, so they should be there, but
		; the check has to shift through them, so we check them as well.
		;
		xor	a
		ld	e,a		; keep the count in E
		; to test, we shift an enable bit through the address enable
		; registers and check the feedback at every other enable
		; (the high enable)
		;
		; first, clear the enables
		out	(BRKENCLR),a	; (the data doesn't matter)
		dec	a		; put a 1 in bit 7 for the enable
		out	(BRKENCLK),a	; shift an enable into Break-1 addr low enable
		xor	a		;  only run a single enable bit through the registers
		out	(BRKENCLK),a	;  high enable
		ld	b,14		; this is the most we support
initbrkt:	in	a,(PCADDR_RD)	; this includes the break hardware detect bit
		and	BRK_HWD_M
		jr	z,initbrkc	; if the read bit is zero (pin HIGH) the hardware isn't there
		; hardware is there
		inc	e		; bump the count
		xor	a		;  make sure to shift in a 0 to the lower level
		out	(BRKENCLK),a	;  next - low enable
		out	(BRKENCLK),a	;  next - high enable
		djnz	initbrkt
initbrkc:	; we have the hardware breakpoint count in E
		ld	a,e
		ld	(baucnt),a
		;
		; see if the target is the SBC (same board)
		in	a,(PCADDR_RD)
		and	SBCMODE_M
		ld	b,SBCMODE_B
initsbcf:	srl	a		; move the SBC indicator into bit 0
		djnz	initsbcf
		ld	(sflag),a	; save it. it is added to our status when we send to DOC.
		;
		; that's it (the CPLD takes care of most of the init)
		; Setting the ZID initialized bit in the CPLD also allows
		; NMI via the DOC ATTN.
		;
		; No need to read and modify, as the SBC can't have run yet.
		ld	a,ZIDINIT_M	; indicate that we are ready (allows NMI from DOC)
		out	(BRDCTRL),a
		; now let DOC know that we've initialized
		;  and go idle...
		jp	doc_wrdy	

		.align	2
		.byte	"!dbmon!"
		.end
